asr_model: "nvidia/canary-1b-v2"
llm_model: "Qwen/Qwen3.6-35B-A3B-FP8"
tts_model: "Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign"
data_dir: "./data"

perturb_input: true
input_request_output_file: "dataset.jsonl"
asr_output_file: "dataset_asr.jsonl"
llm_output_file: "dataset_llm.jsonl"
tts_output_file: "dataset_tts.jsonl"
final_output_file: "dataset_eval.jsonl"